job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      #docker login cloud.canister.io:5000 --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export DEBIAN_FRONTEND=noninteractive
      #apt-get install curl -y
      apt-get update
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      cargo build --release
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
