job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      #docker login cloud.canister.io:5000 --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install wget -y
      wget https://sh.rustup.rs -O rustup.sh
      sh rustup.sh -y
      source $HOME/.cargo/env
      cargo build --release
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
