job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      echo "1"
      docker login cloud.canister.io:5000 -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo "======"
  - name: website
    run: |
      echo "2"
      docker login cloud.canister.io:5000 -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo "======"
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      MAJOR_VERSION: 2.0.
