job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
env:
  DOCKER_USERNAME: ${DOCKER_USERNAME}
  DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  MAJOR_VERSION: 2.0.
stages:
  - name: build
    run: |
      echo "1"
      echo $DOCKER_USERNAME
      echo $DOCKER_PASSWORD
      docker login cloud.canister.io:5000 -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo "======"
    env:
      TEST: "Hello 1111111111111111111111111"

  - name: website
    run: |
      echo "2"
      echo $DOCKER_USERNAME
      echo $DOCKER_PASSWORD
      docker login cloud.canister.io:5000 -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      echo "======"
    env:
      TEST: "Hello 22222222222222222222222222"