job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      ls -l
  - name: website
    run: |
      ls -l
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      MAJOR_VERSION: 2.0.
