job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      docker login cloud.canister.io:5000 --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install wget build-essential -y
      wget https://sh.rustup.rs -O rustup.sh
      sh rustup.sh -y
      source $HOME/.cargo/env
      cargo build --release
      cp target/release/main /out/
      docker build . -t menial_2
      docker tag menial_2 cloud.canister.io:5000/eternalconcert/menial_2:latest
      docker push cloud.canister.io:5000/eternalconcert/menial_2:latest
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
