job: build
image: docker.softcreate.de/builder-menial
env:
  DOCKER_USERNAME: ${DOCKER_USERNAME}
  DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  MAJOR_VERSION: 2.0.
stages:
  - name: build
    run: |
      source $HOME/.cargo/env
      cargo build --release
  - name: website
    run: |
      cp target/release/main src/static/menial_2.bin
      tar -zcvf menial_2.tar.gz src/
      cp menial_2.tar.gz website/src/static/

      cd website
      mkdir -p build/styles
      echo '{"menial_hash": "d17ff70e9a043b502b21f8d2ddcf2d55<wbr>b6aa0e066e965ee6d3cf78a9ea533f86", "menial_tar_gz_hash": "ee6701fb4a73108c0c7d67e394c95213<wbr>6facc9e54d37aad3d558ca615d7ce54f", "timestamp": "2023-02-17 20:06:17", "version": "dev"}' > hashvalues.json
      anvil -i src/ -s src/less/ -o build/ -t "menial 2" -v hashvalues.json
      tar -czvf menial_website.tar.gz build/
  - name: docker-image
    run: |
      docker login docker.softcreate.de --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export MENIAL_VERSION=$MAJOR_VERSION$BUILDER_RUN
      export DEBIAN_FRONTEND=noninteractive
      ./deployment/generate_index.sh $BUILDER_RUN $MAJOR_VERSION$BUILDER_RUN
      docker build . -t menial_2 --no-cache
      docker tag menial_2 docker.softcreate.de/menial_2:latest
      docker tag menial_2 docker.softcreate.de/menial_2:$BUILDER_RUN
      docker push docker.softcreate.de/menial_2:latest
      docker push docker.softcreate.de/menial_2:$BUILDER_RUN
  - name: save-artifacts
    run: |
      cp target/release/main /out/menial_2.bin
      cp menial_2.tar.gz /out/
      cp menial_website.tar.gz /out/