job: build
image: docker.softcreate.de/builder-menial
env:
  DOCKER_USERNAME: ${DOCKER_USERNAME}
  DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  MAJOR_VERSION: 2.0.
stages:
  - name: build
    run: |
      source $HOME/.cargo/env
      cargo build --release
      cp target/release/main menial_2-linux.bin
  - name: website
    run: |
      cp menial_2-linux.bin website/src/static/menial_2-linux.bin
      tar -zcvf menial_2.tar.gz src/
      cp menial_2.tar.gz website/src/static/

      cd website
      mkdir -p build/styles
      python3 utils/update_values.py dev
      anvil -i src/ -s src/less/ -o build/ -t "menial 2" -v hashvalues.json
      tar -czvf menial_website.tar.gz build/
  - name: docker-image
    run: |
      docker login docker.softcreate.de --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      export MENIAL_VERSION=$MAJOR_VERSION$BUILDER_RUN
      export DEBIAN_FRONTEND=noninteractive
      ./deployment/generate_index.sh $BUILDER_RUN $MAJOR_VERSION$BUILDER_RUN
      docker build . -t menial_2 --no-cache
      docker tag menial_2 docker.softcreate.de/menial_2:latest
      docker tag menial_2 docker.softcreate.de/menial_2:$BUILDER_RUN
      docker push docker.softcreate.de/menial_2:latest
      docker push docker.softcreate.de/menial_2:$BUILDER_RUN
  - name: save-artifacts
    run: |
      cp menial_2-linux.bin /out/menial_2-linux.bin
      cp menial_2.tar.gz /out/
      cp website/menial_website.tar.gz /out/
