job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:

  - name: website
    run: |
      docker login cloud.canister.io:5000 --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      ls -l target/release/
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      MAJOR_VERSION: 2.0.
