job: build
image: cloud.canister.io:5000/eternalconcert/builder-default
stages:
  - name: build
    run: |
      export MENIAL_VERSION=$MAJOR_VERSION$BUILDER_RUN
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install wget build-essential libssl-dev pkg-config -y
      wget https://sh.rustup.rs -O rustup.sh
      sh rustup.sh -y
      source $HOME/.cargo/env
      cargo build --release
      cp target/release/main /out/
      ./deployment/generate_index.sh $BUILDER_RUN $MAJOR_VERSION$BUILDER_RUN
  - name: website
    run: |
      ls -l target/release/
    env:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      MAJOR_VERSION: 2.0.
